name: Compile and test

on:
  push:
    branches:
      - 'develop'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:
    uses: ./.github/workflows/build_and_test.yaml

  publish-jar:
    needs: build
    uses: ./.github/workflows/publish_maven.yaml
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  publish-docker:
    needs: publish-jar
    uses: ./.github/workflows/publish_dockerhub.yaml
    with:
      image-tag: develop
    secrets:
      dockerhub-username: ${{ secrets.DOCKER_HUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}


