name: Compile and test

on:
  push:
    branches:
      - 'bugfix/**'
      - 'feature/**'
      - 'hotfix/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:
    uses: ./.github/workflows/build_and_test.yaml
