name: Publish Maven artifact

on:
  workflow_call:
    secrets:
      github-token:
        description: 'Github token passed from the caller workflow'
        required: true

jobs:
  publish-jar:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Publish package
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
