name: Publish Docker image to DockerHub

on:
  workflow_call:
    inputs:
      image-tag:
        description: 'Docker image tag'
        required: true
        type: string
    secrets:
      dockerhub-username:
        description: 'Dockerhub username passed from the caller workflow'
        required: true
      dockerhub-token:
        description: 'Dockerhub token passed from the caller workflow'
        required: true
jobs:
  publish-dockerhub:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.dockerhub-username }}
          password: ${{ secrets.dockerhub-token }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ${{ secrets.dockerhub-username }}/minikube-test:${{ inputs.image-tag }}
